// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Exoscale.Outputs
{

    [OutputType]
    public sealed class DatabaseOpensearchDashboards
    {
        public readonly bool? Enabled;
        public readonly int? MaxOldSpaceSize;
        public readonly int? RequestTimeout;

        [OutputConstructor]
        private DatabaseOpensearchDashboards(
            bool? enabled,

            int? maxOldSpaceSize,

            int? requestTimeout)
        {
            Enabled = enabled;
            MaxOldSpaceSize = maxOldSpaceSize;
            RequestTimeout = requestTimeout;
        }
    }
}
