// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Exoscale.Outputs
{

    [OutputType]
    public sealed class GetBlockStorageVolumeInstanceResult
    {
        /// <summary>
        /// Instance ID.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetBlockStorageVolumeInstanceResult(string id)
        {
            Id = id;
        }
    }
}
