// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Exoscale.Inputs
{

    public sealed class BlockStorageVolumeSnapshotTargetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Snapshot ID.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        public BlockStorageVolumeSnapshotTargetArgs()
        {
        }
        public static new BlockStorageVolumeSnapshotTargetArgs Empty => new BlockStorageVolumeSnapshotTargetArgs();
    }
}
