env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@3c670a7cb92732324c8ccc17f7f9ef9dfca126d0 # v0.0.17
      with:
        kind: all
        email: botdirien.de
        username: dirien-bot
name: Upgrade provider

permissions:
  contents: write

on:
  workflow_dispatch: {}
