// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ❗ Manage service database for a PostgreSQL Exoscale [Database Services (DBaaS)](https://community.exoscale.com/documentation/dbaas/).
 */
export class DbaasPgDatabase extends pulumi.CustomResource {
    /**
     * Get an existing DbaasPgDatabase resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DbaasPgDatabaseState, opts?: pulumi.CustomResourceOptions): DbaasPgDatabase {
        return new DbaasPgDatabase(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'exoscale:index/dbaasPgDatabase:DbaasPgDatabase';

    /**
     * Returns true if the given object is an instance of DbaasPgDatabase.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DbaasPgDatabase {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DbaasPgDatabase.__pulumiType;
    }

    /**
     * ❗ The name of the database for this service.
     */
    declare public readonly databaseName: pulumi.Output<string>;
    /**
     * Default string sort order (LC_COLLATE) for PostgreSQL database
     */
    declare public readonly lcCollate: pulumi.Output<string | undefined>;
    /**
     * Default character classification (LC_CTYPE) for PostgreSQL database
     */
    declare public readonly lcCtype: pulumi.Output<string | undefined>;
    /**
     * ❗ The name of the database service.
     */
    declare public readonly service: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.DbaasPgDatabaseTimeouts | undefined>;
    /**
     * ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
     */
    declare public readonly zone: pulumi.Output<string>;

    /**
     * Create a DbaasPgDatabase resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DbaasPgDatabaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DbaasPgDatabaseArgs | DbaasPgDatabaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DbaasPgDatabaseState | undefined;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["lcCollate"] = state?.lcCollate;
            resourceInputs["lcCtype"] = state?.lcCtype;
            resourceInputs["service"] = state?.service;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["zone"] = state?.zone;
        } else {
            const args = argsOrState as DbaasPgDatabaseArgs | undefined;
            if (args?.databaseName === undefined && !opts.urn) {
                throw new Error("Missing required property 'databaseName'");
            }
            if (args?.service === undefined && !opts.urn) {
                throw new Error("Missing required property 'service'");
            }
            if (args?.zone === undefined && !opts.urn) {
                throw new Error("Missing required property 'zone'");
            }
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["lcCollate"] = args?.lcCollate;
            resourceInputs["lcCtype"] = args?.lcCtype;
            resourceInputs["service"] = args?.service;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["zone"] = args?.zone;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DbaasPgDatabase.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DbaasPgDatabase resources.
 */
export interface DbaasPgDatabaseState {
    /**
     * ❗ The name of the database for this service.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Default string sort order (LC_COLLATE) for PostgreSQL database
     */
    lcCollate?: pulumi.Input<string>;
    /**
     * Default character classification (LC_CTYPE) for PostgreSQL database
     */
    lcCtype?: pulumi.Input<string>;
    /**
     * ❗ The name of the database service.
     */
    service?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.DbaasPgDatabaseTimeouts>;
    /**
     * ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
     */
    zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DbaasPgDatabase resource.
 */
export interface DbaasPgDatabaseArgs {
    /**
     * ❗ The name of the database for this service.
     */
    databaseName: pulumi.Input<string>;
    /**
     * Default string sort order (LC_COLLATE) for PostgreSQL database
     */
    lcCollate?: pulumi.Input<string>;
    /**
     * Default character classification (LC_CTYPE) for PostgreSQL database
     */
    lcCtype?: pulumi.Input<string>;
    /**
     * ❗ The name of the database service.
     */
    service: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.DbaasPgDatabaseTimeouts>;
    /**
     * ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
     */
    zone: pulumi.Input<string>;
}
