// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 */
export function getDatabaseUri(args: GetDatabaseUriArgs, opts?: pulumi.InvokeOptions): Promise<GetDatabaseUriResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("exoscale:index/getDatabaseUri:getDatabaseUri", {
        "name": args.name,
        "timeouts": args.timeouts,
        "type": args.type,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getDatabaseUri.
 */
export interface GetDatabaseUriArgs {
    /**
     * Name of database service to match.
     */
    name: string;
    timeouts?: inputs.GetDatabaseUriTimeouts;
    /**
     * The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `redis`).
     */
    type: string;
    /**
     * The Exoscale Zone name.
     */
    zone: string;
}

/**
 * A collection of values returned by getDatabaseUri.
 */
export interface GetDatabaseUriResult {
    /**
     * Default database name
     */
    readonly dbName: string;
    /**
     * Database service hostname
     */
    readonly host: string;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * Name of database service to match.
     */
    readonly name: string;
    /**
     * Admin user password
     */
    readonly password: string;
    /**
     * Database service port
     */
    readonly port: number;
    /**
     * Database service connection schema
     */
    readonly schema: string;
    readonly timeouts?: outputs.GetDatabaseUriTimeouts;
    /**
     * The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `redis`).
     */
    readonly type: string;
    /**
     * Database service connection URI.
     */
    readonly uri: string;
    /**
     * Admin user username
     */
    readonly username: string;
    /**
     * The Exoscale Zone name.
     */
    readonly zone: string;
}
/**
 * ## Example Usage
 */
export function getDatabaseUriOutput(args: GetDatabaseUriOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDatabaseUriResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("exoscale:index/getDatabaseUri:getDatabaseUri", {
        "name": args.name,
        "timeouts": args.timeouts,
        "type": args.type,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getDatabaseUri.
 */
export interface GetDatabaseUriOutputArgs {
    /**
     * Name of database service to match.
     */
    name: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.GetDatabaseUriTimeoutsArgs>;
    /**
     * The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `redis`).
     */
    type: pulumi.Input<string>;
    /**
     * The Exoscale Zone name.
     */
    zone: pulumi.Input<string>;
}
