// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getInstancePoolList(args: GetInstancePoolListArgs, opts?: pulumi.InvokeOptions): Promise<GetInstancePoolListResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("exoscale:index/getInstancePoolList:getInstancePoolList", {
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getInstancePoolList.
 */
export interface GetInstancePoolListArgs {
    /**
     * The Exoscale [Zone][zone] name.
     */
    zone: string;
}

/**
 * A collection of values returned by getInstancePoolList.
 */
export interface GetInstancePoolListResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The list of exoscale_instance_pool.
     */
    readonly pools: outputs.GetInstancePoolListPool[];
    readonly zone: string;
}

export function getInstancePoolListOutput(args: GetInstancePoolListOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetInstancePoolListResult> {
    return pulumi.output(args).apply(a => getInstancePoolList(a, opts))
}

/**
 * A collection of arguments for invoking getInstancePoolList.
 */
export interface GetInstancePoolListOutputArgs {
    /**
     * The Exoscale [Zone][zone] name.
     */
    zone: pulumi.Input<string>;
}
