// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class IAMAPIKey extends pulumi.CustomResource {
    /**
     * Get an existing IAMAPIKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IAMAPIKeyState, opts?: pulumi.CustomResourceOptions): IAMAPIKey {
        return new IAMAPIKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'exoscale:index/iAMAPIKey:IAMAPIKey';

    /**
     * Returns true if the given object is an instance of IAMAPIKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IAMAPIKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IAMAPIKey.__pulumiType;
    }

    /**
     * The IAM API Key to match.
     */
    public /*out*/ readonly key!: pulumi.Output<string>;
    /**
     * ❗ IAM API Key name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * ❗ IAM API role ID.
     */
    public readonly roleId!: pulumi.Output<string>;
    /**
     * Secret for the IAM API Key.
     */
    public /*out*/ readonly secret!: pulumi.Output<string>;
    public readonly timeouts!: pulumi.Output<outputs.IAMAPIKeyTimeouts | undefined>;

    /**
     * Create a IAMAPIKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IAMAPIKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IAMAPIKeyArgs | IAMAPIKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IAMAPIKeyState | undefined;
            resourceInputs["key"] = state ? state.key : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["roleId"] = state ? state.roleId : undefined;
            resourceInputs["secret"] = state ? state.secret : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
        } else {
            const args = argsOrState as IAMAPIKeyArgs | undefined;
            if ((!args || args.roleId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'roleId'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["roleId"] = args ? args.roleId : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IAMAPIKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IAMAPIKey resources.
 */
export interface IAMAPIKeyState {
    /**
     * The IAM API Key to match.
     */
    key?: pulumi.Input<string>;
    /**
     * ❗ IAM API Key name.
     */
    name?: pulumi.Input<string>;
    /**
     * ❗ IAM API role ID.
     */
    roleId?: pulumi.Input<string>;
    /**
     * Secret for the IAM API Key.
     */
    secret?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.IAMAPIKeyTimeouts>;
}

/**
 * The set of arguments for constructing a IAMAPIKey resource.
 */
export interface IAMAPIKeyArgs {
    /**
     * ❗ IAM API Key name.
     */
    name?: pulumi.Input<string>;
    /**
     * ❗ IAM API role ID.
     */
    roleId: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.IAMAPIKeyTimeouts>;
}
